Repository GDG-ZIMEET/ZIMEET-FrontEnd, pull requests merged in 2025-02, with the labels that each got.

#106 [#50] refactor: 2대2 페이지 디자인 수정사항
  src/components/Meeting22/Team/Styles.js
Labels: 🛠️ Refactor

#96 [#95] 프로필 수정 페이지 퍼블리싱
  src/components/MyPage/ModifyNickname/ModifyNickname.jsx
  src/components/MyPage/ModifyNickname/Styles.js
  src/pages/MyPage/ModifyEmoji.jsx/SelectEmoji.jsx
  src/pages/MyPage/ModifyEmoji.jsx/StylesEmoji.js
  src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
  src/pages/MyPage/ModifyProfile/Styles.js
  src/pages/Routers.tsx
Labels: ✨Feat

#94 [#93] 마이페이지 메인 ui 수정
  src/components/MyPage/Event/Styles.js
  src/components/MyPage/QnA/Styles.js
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
Labels: 🛠️ Refactor

#116 [#115] refactor : api 구조 변경
  src/api/axiosConfig.ts
  src/api/booth/GetboothDetail.ts
  src/api/booth/Getbooths.ts
Labels: 🛠️ Refactor

#113 [#112]feat:2대2, 3대3 페이지 구분 로직 추가
  src/components/Meeting22/Team/Styles.js
  src/components/Meeting22/Team/Team.jsx
  src/components/Meeting22/TeamBox/TeamBox.jsx
  src/components/Meeting22/TypeButton/TypeButton.tsx
  src/recoil/state/teamSizeState.js
Labels: ✨Feat

#124 [#123] feat : 인증버튼 수정 및 동그라미 수정
  src/assets/icon/Meeting22/VerifyIcon.svg
  src/assets/icon/Meeting22/certification.svg
  src/components/Meeting22/MakeTeam/MakeTeam.jsx
  src/components/Meeting22/MakeTeam/Styles.js
  src/components/Meeting22/Team/Styles.js
  src/components/Meeting22/Team/Team.jsx
  src/components/Meeting22/ViewMore/Styles.js
Labels: ✨Feat, 🛠️ Refactor

#126 [#125]design: 우리팀 소개 페이지 헤더 수정
  src/components/OurTeamIntro/Header/Header.jsx
  src/components/OurTeamIntro/Header/Styles.js
Labels: 🎨 Design

#128 [#127]design:모달 Hi 아이콘 적용 및 레이아웃 수정
  src/assets/icon/TeamInfo/HiIcon.svg
  src/components/Meeting22/TeamMaking/Profile/Styles.ts
  src/components/OurTeamIntro/Header/Header.jsx
  src/components/OurTeamIntro/Header/Styles.js
  src/components/OurTeamIntro/Modal/TipModal/Styles.js
  src/components/OurTeamIntro/Profile/MyProfile.jsx
  src/components/OurTeamIntro/Profile/ProfileDetail/ProfileDetail.jsx
  src/components/OurTeamIntro/Profile/ProfileDetail/Styles.js
  src/components/OurTeamIntro/Profile/Styles.js
  src/components/TeamIntro/Header/Styles.js
  src/components/TeamIntro/Modal/Heart/Heart.jsx
  src/components/TeamIntro/Modal/Heart/Styles.js
  src/components/TeamIntro/Modal/SendQuestion/SendQuestion.jsx
  src/components/TeamIntro/Modal/SendQuestion/Styles.js
  src/components/TeamIntro/Profile/MyProfile.jsx
  src/components/TeamIntro/Profile/ProfileData.js
  src/components/TeamIntro/Profile/ProfileDetail/ProfileDetail.jsx
  src/components/TeamIntro/Profile/ProfileDetail/Styles.js
  src/components/TeamIntro/Profile/Styles.js
  src/pages/OurTeamIntro/OurTeamIntro.jsx
  src/pages/OurTeamIntro/Styles.js
  src/pages/TeamIntro/Styles.js
Labels: ✨Feat, 🎨 Design

#132 [#122] 마이페이지 네비게이션바 수정
  src/assets/Icons.ts
  src/assets/icon/navigationbar/Smyinformation.svg
  src/components/NavigationBar/NavigationBar.jsx
  src/components/NavigationBar/Styles.js
  src/pages/MyPage/MyPage/Styles.js
Labels: 🛠️ Refactor

#133 [#131] design: 미팅 네비게이션 수정
  src/assets/Icons.ts
  src/assets/icon/navigationbar/HeartN.svg
  src/components/NavigationBar/Styles.js
Labels: 🎨 Design

#109 [#108] 로그인 api 연결
  src/pages/Authentication/Login/Login.jsx
  src/pages/Authentication/Login/Styles.js
  src/recoil/state/authAtom.js
Labels: ✨Feat

#135 [#134] 로그인 api 리팩토링
  src/api/Authentication/useLogin.js
  src/components/NavigationBar/NavigationBar.jsx
  src/pages/Authentication/Login/Login.jsx
  src/pages/Meeting22/Meeting22.jsx
  src/recoil/state/authState.js
Labels: 🛠️ Refactor

#137 [#136] 토스폰트 이모지로 수정
  src/pages/Authentication/Join/Join2.jsx
  src/pages/Authentication/Join/SelectEmoji.jsx
  src/pages/Authentication/Join/Styles3.js
  src/pages/Authentication/Join/StylesEmoji.js
  src/pages/MyPage/ModifyEmoji.jsx/ModifyEmoji.jsx
  src/pages/MyPage/ModifyEmoji.jsx/Styles.js
  src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
  src/pages/MyPage/ModifyProfile/Styles.js
  src/pages/Routers.tsx
Labels: 🛠️ Refactor

#141 [#140] api연결 및 ts 구조 설정
  src/api/Meeting/GetTeamGallery.ts
  src/components/Meeting22/Team/Styles.ts
  src/components/Meeting22/Team/Team.jsx
  src/components/Meeting22/Team/Team.tsx
  src/components/Meeting22/TeamBox/Styles.ts
  src/components/Meeting22/TeamBox/TeamBox.jsx
  src/components/Meeting22/TeamBox/TeamBox.tsx
  src/components/Meeting22/TypeButton/TypeButton.tsx
  src/components/NavigationBar/NavigationBar.jsx
  src/pages/Meeting22/Meeting22.jsx
  src/pages/Meeting22/Meeting22.tsx
  src/pages/Meeting22/Styles.ts
  src/pages/MeetingRandom/MeetingRandom.tsx
  src/pages/MeetingRandom/MeetingRoading/MeetingRoading.tsx
  src/recoil/state/authState.js
  src/recoil/state/authState.ts
  src/recoil/type/teamGallery.ts
Labels: ✨Feat, 🚨 BugFix, 🛠️ Refactor

#143 [#142] refactor : 팀 갤러리 ui 수정, 3대3 음악 변환
  package-lock.json
  package.json
  src/components/Meeting22/LoginPopUp/LoginPopUp.jsx
  src/components/Meeting22/LoginPopUp/Styles.js
  src/components/Meeting22/Team/Styles.ts
  src/components/Meeting22/Team/Team.tsx
  src/components/Meeting22/TeamBox/Styles.ts
  src/components/Meeting22/TeamBox/TeamBox.tsx
  src/components/Meeting22/TypeButton/Styles.ts
  src/components/NavigationBar/Styles.js
  src/data/NonLoginData.ts
  src/pages/Meeting22/Meeting22.tsx
  src/pages/Meeting22/Styles.ts
Labels: ✨Feat, 🛠️ Refactor

#145 [#144] feat: 팀 갤러리에서 우리팀 조회 api
  src/api/Meeting/GetTeamGallery.ts
  src/api/Meeting/GetourTeam.ts
  src/components/Meeting22/MakeTeam/MakeTeam.jsx
  src/components/Meeting22/MakeTeam/MakeTeam.tsx
  src/components/Meeting22/MakeTeam/Styles.ts
  src/components/Meeting22/Team/Styles.ts
  src/components/Meeting22/Team/Team.tsx
  src/components/Meeting22/TeamBox/Styles.ts
  src/components/Meeting22/TeamBox/TeamBox.tsx
  src/components/Meeting22/TypeButton/TypeButton.tsx
  src/components/Meeting22/ViewMore/Styles.ts
  src/components/Meeting22/ViewMore/ViewMore.tsx
  src/pages/Meeting22/Meeting22.tsx
  src/recoil/selectors/exampleSelector.ts
  src/recoil/state/exampleState.ts
  src/recoil/state/teamSizeState.js
  src/recoil/type/Meeting/ourTeamType.ts
  src/recoil/type/Meeting/teamGallery.ts
Labels: ✨Feat

#147 [#146] feat: 우리 팀 상세페이지 api 제작
  src/api/Meeting/GetourTeamDetail.ts
  src/assets/icon/TeamInfo/ZimeetLogo.svg
  src/assets/icon/TeamInfo/whiteGo.svg
  src/components/Meeting22/MakeTeam/MakeTeam.tsx
  src/components/Meeting22/ViewMore/ViewMore.tsx
  src/components/OurTeamIntro/Modal/Certification/Certification.tsx
  src/components/OurTeamIntro/Modal/Certification/Styles.ts
  src/components/OurTeamIntro/Modal/TipModal/Styles.js
  src/components/OurTeamIntro/Modal/TipModal/TipModal.jsx
  src/components/OurTeamIntro/Profile/AgeBox/Styles.js
  src/components/OurTeamIntro/Profile/MyProfile.jsx
  src/components/OurTeamIntro/Profile/MyProfile.tsx
  src/components/OurTeamIntro/Profile/ProfileData.js
  src/components/OurTeamIntro/Profile/ProfileDetail/Styles.js
  src/components/OurTeamIntro/Profile/Styles.ts
  src/pages/OurTeamIntro/OurTeamIntro.jsx
  src/pages/OurTeamIntro/OurTeamIntro.tsx
  src/pages/OurTeamIntro/Styles.js
  src/pages/OurTeamIntro/Styles.ts
  src/recoil/type/Meeting/TeamDetail.ts
Labels: ✨Feat, 🛠️ Refactor

#149 [#148] featute: 팀 상세 조회 api 연결
  src/api/Meeting/GetTeamDetail.ts
  src/api/Meeting/GetourTeamDetail.ts
  src/components/Meeting22/Team/Team.tsx
  src/components/OurTeamIntro/Profile/AgeBox/Styles.js
  src/components/TeamIntro/Modal/Detail/Styles.js
  src/components/TeamIntro/Modal/PremiumModal/PremiumModal.tsx
  src/components/TeamIntro/Modal/PremiumModal/Styles.ts
  src/components/TeamIntro/Modal/Send/Styles.js
  src/components/TeamIntro/Modal/SendQuestion/SendQuestion.jsx
  src/components/TeamIntro/Modal/SendQuestion/Styles.js
  src/components/TeamIntro/Profile/AgeBox/Styles.js
  src/components/TeamIntro/Profile/MyProfile.tsx
  src/components/TeamIntro/Profile/ProfileData.js
  src/components/TeamIntro/Profile/ProfileDetail/Styles.js
  src/components/TeamIntro/Profile/Styles.ts
  src/pages/OurTeamIntro/OurTeamIntro.tsx
  src/pages/Routers.tsx
  src/pages/TeamIntro/Styles.js
  src/pages/TeamIntro/Styles.ts
  src/pages/TeamIntro/TeamIntro.tsx
  src/recoil/type/Meeting/TeamDetail.ts
Labels: ✨Feat, 🛠️ Refactor

#151 [#150] feat: 팀만들기 안내 toast
  src/components/Meeting22/MakeTeam/MakeTeam.tsx
  src/components/Meeting22/Team/Team.tsx
  src/components/Meeting22/Team/TeamData.js
  src/components/Meeting22/TeamBox/TeamBox.tsx
  src/components/Meeting22/Toast/Styles.ts
  src/components/Meeting22/Toast/Toast.tsx
  src/pages/Meeting22/Meeting22.tsx
Labels: ✨Feat

#155 [#154] refactor: 헤더수정
  src/assets/Icons.ts
  src/assets/icon/booth/D grey.svg
  src/assets/icon/booth/D.svg
  src/assets/icon/booth/DGoCCUK.svg
  src/assets/icon/booth/G grey.svg
  src/assets/icon/booth/G.svg
  src/assets/icon/booth/GB.svg
  src/assets/icon/booth/ateway.svg
  src/assets/icon/booth/ating.svg
  src/assets/icon/booth/headerLogo.svg
  src/components/Booth/Header/Styles.ts
  src/components/Booth/TypeButton/Styles.ts
  src/pages/Introduct/GdgocIntroduct/Styles.ts
  src/pages/Introduct/ZimeetIntroduct/Styles.ts
Labels: 🎨 Design, 🛠️ Refactor

#159 [#156]feat: 팀 상세페이지에서 팀 이름 조회 api
  src/components/TeamIntro/Header/Header.jsx
  src/components/TeamIntro/Header/Header.tsx
  src/components/TeamIntro/Header/Styles.js
  src/components/TeamIntro/Header/Styles.ts
  src/pages/TeamIntro/TeamIntro.tsx
Labels: ✨Feat, 📬 API

#162 [#161] 회원가입 전화번호 추가
  src/pages/Authentication/Join/Join.jsx
  src/recoil/state/joinState.js
Labels: 🛠️ Refactor

#163 [#160] 팀 상세조회에서 성별에 따른 색 변화
  src/components/TeamIntro/Profile/MyProfile.tsx
  src/components/TeamIntro/Profile/ProfileDetail/ProfileDetail.jsx
  src/components/TeamIntro/Profile/ProfileDetail/ProfileDetail.tsx
  src/components/TeamIntro/Profile/ProfileDetail/Styles.ts
  src/pages/TeamIntro/TeamIntro.tsx
  tsconfig.json
Labels: ✨Feat, 📬 API

#165 [#164] feat: 우리팀 성별 마다 색 변경
  src/components/OurTeamIntro/Profile/MyProfile.tsx
  src/components/OurTeamIntro/Profile/ProfileDetail/ProfileDetail.jsx
  src/components/OurTeamIntro/Profile/ProfileDetail/ProfileDetail.tsx
  src/components/OurTeamIntro/Profile/ProfileDetail/Styles.ts
  src/pages/OurTeamIntro/OurTeamIntro.tsx
Labels: ✨Feat, 📬 API

#166 [#103] 받은 하이, 보낸 하이 팀 프로필 UI 퍼블리싱
  src/components/Chatting/ReceiveHi/Modal/AcceptHiModal/AcceptHiModal.tsx
  src/components/Chatting/ReceiveHi/Modal/AcceptHiModal/Styles.ts
  src/components/Chatting/ReceiveHi/Modal/AcceptedHiModal/AcceptedHiModal.tsx
  src/components/Chatting/ReceiveHi/Modal/AcceptedHiModal/Styles.ts
  src/components/Chatting/ReceiveHi/Modal/RefuseHiModal/RefuseHiModal.tsx
  src/components/Chatting/ReceiveHi/Modal/RefuseHiModal/Styles.ts
  src/components/Chatting/ReceiveHi/Modal/RefusedHiModal/RefusedHiModal.tsx
  src/components/Chatting/ReceiveHi/Modal/RefusedHiModal/Styles.ts
  src/components/TeamIntro/Button/Heart/Heart.jsx
  src/components/TeamIntro/Button/Heart/Styles.js
  src/components/TeamIntro/Button/SentHiButton/SentHiButton.tsx
  src/components/TeamIntro/Button/SentHiButton/Styles.ts
  src/components/TeamIntro/Modal/Detail/Styles.js
  src/components/TeamIntro/Modal/PremiumModal/Styles.ts
  src/components/TeamIntro/Profile/ProfileData.js
  src/pages/Chatting/ReceivedHiTeam/ReceivedHiTeam.tsx
  src/pages/Chatting/ReceivedHiTeam/Styles.ts
  src/pages/Routers.tsx
  src/pages/TeamIntro/TeamIntro.tsx
Labels: ✨Feat, 🎨 Design

#168 [#167] 받은하이 팀 프로필 디자인 수정
  src/components/TeamIntro/Header/Styles.ts
  src/pages/Chatting/ReceivedHiTeam/ReceivedHiTeam.tsx
  src/pages/Chatting/ReceivedHiTeam/Styles.ts
Labels: 🚨 BugFix, 🎨 Design

#170 [#169]feat: 팀명 중복 확인 api 연결
  src/api/Meeting/GetCheckDuplicate.ts
  src/components/Meeting22/TeamMaking/TeamName/Styles.ts
  src/components/Meeting22/TeamMaking/TeamName/TeamName.tsx
Labels: ✨Feat, 📬 API

#172 [#171]feat: 공통 헤더 컴포넌트
  src/components/Common/Header/Header/Header.tsx
  src/components/Common/Header/Header/Styles.ts
  src/components/Common/Header/HeaderName/Header.tsx
  src/components/Common/Header/HeaderName/Styles.ts
Labels: ✨Feat

#174 [#173] 회원가입 api 연결
  src/api/Authentication/PostJoin.ts
  src/components/Authentication/Join/LogoContainer/LogoContainer.tsx
  src/components/Authentication/Join/LogoContainer/Styles.ts
  src/components/Authentication/Join/SelectEmoji/Header/Header.jsx
  src/pages/Authentication/Join/Join1/Join.jsx
  src/pages/Authentication/Join/Join1/Styles.js
  src/pages/Authentication/Join/Join2.jsx
  src/pages/Authentication/Join/Join2/Join2.jsx
  src/pages/Authentication/Join/Join2/Styles.js
  src/pages/Authentication/Join/Join3.jsx
  src/pages/Authentication/Join/Join3/Join3.jsx
  src/pages/Authentication/Join/Join3/Styles.js
  src/pages/Authentication/Join/SelectEmoji.jsx
  src/pages/Authentication/Join/SelectEmoji/SelectEmoji.jsx
  src/pages/Authentication/Join/SelectEmoji/Styles.js
  src/pages/Authentication/Join/Styles2.js
  src/pages/Authentication/Join/StylesEmoji.js
  src/pages/Routers.tsx
  src/recoil/state/joinState.js
  src/recoil/type/Authentication/JoinType.ts
Labels: ✨Feat, 📬 API

#179 [#178] feat: 팀 생성에서 내 정보 조회
  src/api/Mypage/GetmyProfile.ts
  src/api/TeamMaking/GetCheckDuplicate.ts
  src/api/TeamMaking/GetSearchTeamMembers.ts
  src/api/TeamMaking/GetUserProfile.ts
  src/components/Meeting22/MakeTeam/MakeTeam.tsx
  src/components/Meeting22/TeamMaking/Profile/AgeBox/AgeBox.tsx
  src/components/Meeting22/TeamMaking/Profile/AgeBox/Styles.ts
  src/components/Meeting22/TeamMaking/Profile/MyProfile.tsx
  src/components/Meeting22/TeamMaking/Profile/ProfileData.ts
  src/components/Meeting22/TeamMaking/Profile/ProfileDetail/ProfileDetail.tsx
  src/components/Meeting22/TeamMaking/Profile/ProfileDetail/Styles.ts
  src/components/Meeting22/TeamMaking/Profile/Styles.ts
  src/components/Meeting22/TeamMaking/Teams/TeamData.tsx
  src/components/Meeting22/TeamMaking/Teams/Teams.tsx
  src/components/OurTeamIntro/Profile/MyProfile.tsx
  src/components/OurTeamIntro/Profile/Styles.ts
  src/recoil/state/authState.ts
  src/recoil/type/MyPage/MyProfileType.ts
  src/recoil/type/TeamMaking/SearchTeamMember.ts
  src/recoil/type/TeamMaking/UserType.ts
Labels: ✨Feat

#181 [#180] feat: 검색 api 연결
  src/components/Meeting22/TeamMaking/Modal/TeamMemberModal.tsx
  src/components/Meeting22/TeamMaking/TeamName/TeamName.tsx
  src/recoil/type/TeamMaking/SearchTeamMember.ts
Labels: 📬 API

#189 [#188] refactor: 코드구조 리펙토링 및 ui 변경
  src/components/Authentication/Join/JoinModal/Modal.jsx
  src/components/Authentication/Join/JoinModal/StylesModal.js
  src/components/Common/Header/Header/Header.tsx
  src/components/Common/Header/Header/Styles.ts
  src/components/Common/NavigationBar/NavigationBar.jsx
  src/components/Common/NavigationBar/Styles.js
  src/components/Common/Profile/AgeBox/AgeBox.jsx
  src/components/Common/Profile/AgeBox/Styles.js
  src/components/Common/Profile/MyProfile.tsx
  src/components/Common/Profile/ProfileDetail/ProfileDetail.tsx
  src/components/Common/Profile/ProfileDetail/Styles.ts
  src/components/Common/Profile/Styles.ts
  src/components/Meeting22/TeamMaking/Header/Header.tsx
  src/components/Meeting22/TeamMaking/Header/Styles.ts
  src/components/Meeting22/TeamMaking/Teams/Teams.tsx
  src/components/OurTeamIntro/Profile/MyProfile.tsx
  src/components/TeamMaking/Buttons/MakingButton/MakingButton.tsx
  src/components/TeamMaking/Buttons/MakingButton/SituationText.tsx
  src/components/TeamMaking/Buttons/MakingButton/Styles.ts
  src/components/TeamMaking/Buttons/PlusButton/PeoplePlusButton.tsx
  src/components/TeamMaking/Buttons/PlusButton/Styles.ts
  src/components/TeamMaking/Modal/Styles.ts
  src/components/TeamMaking/Modal/TeamMemberModal.tsx
  src/components/TeamMaking/TeamName/Styles.ts
  src/components/TeamMaking/TeamName/TeamName.tsx
  src/components/TeamMaking/Teams/Styles.ts
  src/components/TeamMaking/Teams/Teams.tsx
  src/data/SignUpData.ts
  src/pages/Authentication/Join/Join3/Join3.jsx
  src/pages/Booth/Booth.tsx
  src/pages/Booth/BoothDetail/BoothDetail.tsx
  src/pages/Chatting/ChattingInventory/ChattingInventory.tsx
  src/pages/Chatting/ReceiveHi/ReceiveHi.tsx
  src/pages/Chatting/ReceivedHiTeam/ReceivedHiTeam.tsx
  src/pages/Chatting/SentHi/SentHi.tsx
  src/pages/Introduct/GdgocIntroduct/GdgocIntroduct.tsx
  src/pages/Introduct/ZimeetIntroduct/ZimeetIntroduct.tsx
  src/pages/Meeting22/Meeting22.tsx
  src/pages/MeetingRandom/Help/Help.tsx
  src/pages/MeetingRandom/MeetingRandom.tsx
  src/pages/MeetingRandom/MeetingRoading/MeetingRoading.tsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/NonMember/Meeting/Meeting.tsx
  src/pages/OurTeamIntro/OurTeamIntro.tsx
  src/pages/Routers.tsx
  src/pages/TeamIntro/TeamIntro.tsx
  src/pages/TeamMaking/Styles.ts
  src/pages/TeamMaking/TeamMaking.tsx
Labels: 🛠️ Refactor

#191 [#190] feat: 팀삭제 api 연결 및 삭제 가능 개수 조회
  src/api/TeamMaking/DeleteTeam.ts
  src/api/TeamMaking/GetTeamdeleteCount.ts
  src/components/OurTeamIntro/Header/Header.tsx
  src/components/OurTeamIntro/Header/Styles.ts
  src/components/OurTeamIntro/Modal/DeleteModal/DeleteModal.jsx
  src/components/OurTeamIntro/Modal/DeleteModal/DeleteModal.tsx
  src/components/OurTeamIntro/Modal/DeleteModal/Styles.ts
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/OurTeamIntro/OurTeamIntro.tsx
Labels: ✨Feat, 📬 API

#193 [#192] 마이페이지 api 연결
  src/assets/icon/login/zimeetLogo.svg
  src/components/MyPage/ItemShop/ItemBanner/ItemBanner.jsx
  src/components/MyPage/ItemShop/ItemBanner/Styles.js
  src/components/MyPage/ItemShop/Main/ItemShop.jsx
  src/components/MyPage/QnA/QnA.jsx
  src/components/MyPage/QnA/Styles.js
  src/components/OurTeamIntro/Modal/DeleteModal/Styles.ts
  src/pages/Meeting22/Meeting22.tsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
Labels: ✨Feat, 📬 API

#197 [#196] 회원정보수정 페이지 api 연결
  src/api/Mypage/UpdateEmoji.ts
  src/api/Mypage/UpdateNickname.ts
  src/components/MyPage/ModifyNickname/ModifyNickname.jsx
  src/components/MyPage/ModifyNickname/Styles.js
  src/pages/MyPage/ModifyEmoji.jsx/ModifyEmoji.jsx
  src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
  src/pages/MyPage/ModifyProfile/Styles.js
Labels: ✨Feat, 📬 API

#195 [#194] 회원가입 정규식 추가
  src/pages/Authentication/Join/Join1/Join.jsx
  src/pages/Authentication/Join/Join1/Styles.js
  src/pages/Authentication/Join/Join2/Join2.jsx
  src/pages/Authentication/Join/Join2/Styles.js
Labels: ✨Feat

#198 [#194] 회원가입 phoneNumber 추가
  src/pages/Authentication/Join/Join1/Join.jsx
  src/recoil/state/joinState.js
Labels: 🚨 BugFix

#200 [#199] 마이페이지에 프로필수정페이지 연결
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
Labels: 🛠️ Refactor

#205 [#204] feat: 노션 웹 뷰 공통 컴포넌트 제작
  src/components/MeetingRandom/MeetingRandomMain.tsx
  src/pages/Notion/NotionMain.tsx
  src/pages/Notion/Styles.ts
  src/pages/Routers.tsx
Labels: ✨Feat

#208 [#203] feat: 로딩 ui 제작
  src/components/Chatting/ChattingInventory/Teams/Styles.ts
  src/components/Chatting/ChattingInventory/Teams/Teams.tsx
  src/components/Common/Loading/Styles.ts
  src/components/Common/Loading/loading.tsx
Labels: ✨Feat
