Repository GDG-ZIMEET/ZIMEET-FrontEnd, pull requests merged in 2025-03, with the labels that each got.

#219 [#218] 마이 로딩화면 추가
  src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
  src/pages/MyPage/ModifyProfile/Styles.js
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
Labels: 🛠️ Refactor

#216 [#215] 로그인 쿠키 변경 및 오류 수정
  package-lock.json
  src/api/Authentication/useLogin.js
  src/api/Authentication/useLoginCheck.js
  src/components/MainScreen.tsx
  src/pages/Meeting22/Meeting22.tsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/recoil/state/authState.ts
Labels: 🛠️ Refactor

#225 [#218] 로딩 크기 수정
  src/pages/MyPage/ModifyProfile/Styles.js
  src/pages/MyPage/MyPage/Styles.js
Labels: 🛠️ Refactor

#227 [#220] 로그아웃, 회원탈퇴 모달 퍼블리싱
  package-lock.json
  package.json
  src/components/MyPage/ModalLogout/ModalLogout.jsx
  src/components/MyPage/ModalLogout/Styles.js
  src/components/MyPage/ModalWithdraw/ModalWithdraw.jsx
  src/components/MyPage/ModalWithdraw/Styles.js
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
Labels: ✨Feat

#226 [#224]feat: 채팅 사용자 상세정보 가져오기
  src/components/Chatting/Chat/Sidebar/ChatSidebar.tsx
  src/components/Chatting/ExitModal/ExitModal.tsx
  src/components/Chatting/ExitModal/Styles.ts
  src/components/Chatting/ReceiveHi/Teams/Teams.tsx
  src/components/Common/Profile/ProfileDetail/ProfileDetail.tsx
  src/components/Common/Profile/ProfileDetail/Styles.ts
  src/components/TeamMaking/Teams/Teams.tsx
  src/pages/Chatting/Chatting/Chatting.tsx
  src/pages/Chatting/UserDetail/ChatUserdetail.tsx
  src/pages/Chatting/UserDetail/Styles.ts
  src/pages/Routers.tsx
Labels: ✨Feat, 📬 API

#232 [#231] 마이 ui 수정
  src/assets/Icons.ts
  src/assets/icon/MyPage/Ticket.svg
  src/assets/icon/MyPage/Ticket1.svg
  src/assets/icon/MyPage/Ticket3.svg
  src/assets/icon/MyPage/Ticket8.svg
  src/components/Common/Header/Header/Header.tsx
  src/components/MyPage/ItemShop/Hi33/ItemHi33.jsx
  src/components/MyPage/ModifyNickname/ModifyNickname.jsx
  src/components/MyPage/ModifyNickname/Styles.js
  src/pages/MyPage/ModifyEmoji.jsx/ModifyEmoji.jsx
  src/pages/MyPage/ModifyEmoji/ModifyEmoji.jsx
  src/pages/MyPage/ModifyEmoji/Styles.js
  src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
  src/pages/Routers.tsx
Labels: 🛠️ Refactor

#233 [#228] 로그아웃 api 연결
  src/api/Authentication/useLogin.js
  src/api/Authentication/useLoginCheck.js
  src/api/Authentication/useLogout.js
  src/components/MyPage/ModalLogout/ModalLogout.jsx
  src/recoil/state/authState.ts
Labels: ✨Feat, 📬 API

#237 [#236] 마이페이지 DOM 오류 수정
  src/components/MyPage/ItemShop/ItemBanner/ItemBanner.jsx
  src/components/MyPage/ItemShop/ItemBanner/Styles.js
  src/components/MyPage/QnA/QnA.jsx
  src/components/MyPage/QnA/Styles.js
  src/pages/MyPage/ModifyEmoji/ModifyEmoji.jsx
  src/pages/MyPage/ModifyEmoji/Styles.js
  src/pages/MyPage/MyPage/MyPage.jsx
Labels: 🛠️ Refactor

#235 [#234] 회원탈퇴 api 연결
  src/api/Authentication/useWithdraw.js
  src/components/MyPage/ModalWithdraw/ModalWithdraw.jsx
Labels: ✨Feat, 📬 API

#239 [238] 회원가입 중복확인 api 연결
  src/api/Authentication/checkDuplicateNickname.js
  src/api/Authentication/checkDuplicateNumber.js
  src/pages/Authentication/Join/Join1/Join.jsx
  src/pages/Authentication/Join/Join2/Join2.jsx
Labels: ✨Feat, 📬 API

#248 [#245] Amplitude 로깅 추가
  package-lock.json
  public/index.html
  src/App.tsx
  src/api/Authentication/useLogin.js
  src/api/Chatting/WebSocketchat.ts
  src/components/Authentication/Join/JoinModal/Modal.jsx
  src/components/Booth/Booths/Booths.tsx
  src/components/Booth/Header/Header.tsx
  src/components/Booth/TypeButton/TypeButton.tsx
  src/components/BoothDetail/AccountCopy/AccountCopy.tsx
  src/components/Chatting/ChattingInventory/ChattingInventoryTypeButton/ChattingInventoryTypeButton.tsx
  src/components/Chatting/ChattingInventory/Teams/Teams.tsx
  src/components/Chatting/ExitModal/ExitModal.tsx
  src/components/Chatting/ReceiveHi/Teams/Teams.tsx
  src/components/Chatting/SentHi/Teams/Teams.tsx
  src/components/Common/NavigationBar/NavigationBar.jsx
  src/components/GotoMeeting/GotoMeeting.tsx
  src/components/Meeting22/LoginPopUp/LoginPopUp.jsx
  src/components/Meeting22/MakeTeam/MakeTeam.tsx
  src/components/Meeting22/Toast/Toast.tsx
  src/components/Meeting22/TypeButton/TypeButton.tsx
  src/components/TeamIntro/Button/Heart/Heart.jsx
  src/components/TeamIntro/Modal/SendQuestion/SendQuestion.tsx
  src/pages/Authentication/Join/Join1/Join.jsx
  src/pages/Authentication/Join/Join2/Join2.jsx
  src/pages/Authentication/Join/Join3/Join3.jsx
  src/pages/Authentication/Join/SelectEmoji/SelectEmoji.jsx
  src/pages/Booth/BoothDetail/BoothDetail.tsx
  src/pages/Chatting/Chatting/Chatting.tsx
  src/pages/Chatting/ChattingInventory/ChattingInventory.tsx
  src/pages/Chatting/ReceiveHi/ReceiveHi.tsx
  src/pages/Chatting/SentHi/SentHi.tsx
  src/pages/Chatting/UserDetail/ChatUserdetail.tsx
  src/pages/Meeting22/Styles.ts
  src/recoil/state/authState.ts
Labels: ✨Feat, 📊 Analytics

#250 [#249] 배포 전 QA BugFix
  src/assets/icon/boothDetail/logo/cinephile_logo.jpeg
  src/assets/icon/boothDetail/poster/cinephile_poster.jpeg
  src/assets/icon/boothDetail/poster/gdgoc_poster.png
  src/components/Booth/Booths/Booths.tsx
  src/components/Booth/Booths/boothsData.ts
  src/components/Booth/TypeButton/TypeButton.tsx
  src/components/BoothDetail/AccountCopy/Styles.ts
  src/components/BoothDetail/BackHeader/BackHeader.tsx
  src/components/BoothDetail/Explanation/Explanation.tsx
  src/components/BoothDetail/ItemInventory/ItemInventory.tsx
  src/components/BoothDetail/ItemInventory/Styles.ts
  src/pages/Authentication/Join/Join3/Join3.jsx
  src/pages/Authentication/Join/Join3/Styles.js
  src/pages/Booth/Booth.tsx
  src/pages/Booth/BoothDetail/BoothDetail.tsx
  src/pages/Booth/BoothDetail/Styles.ts
  src/pages/Introduct/GdgocIntroduct/GdgocIntroduct.tsx
  src/pages/Introduct/ZimeetIntroduct/ZimeetIntroduct.tsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/recoil/state/boothState.ts
  src/recoil/type/booth.ts
  src/utils/ClubLogoMapper.ts
  src/utils/ClubPosterMapper.ts
Labels: 🚨 BugFix

#255 [#251] Amplitude 마이, 미팅 트래킹 추가
  src/api/Meeting/WebRandom.ts
  src/components/Meeting22/Team/Team.tsx
  src/components/MeetingRandom/MeetingRandomMain.tsx
  src/components/MeetingRandom/Modal/Modal.tsx
  src/components/MyPage/ModalWithdraw/ModalWithdraw.jsx
  src/components/MyPage/QnA/QnA.jsx
  src/pages/Meeting22/Meeting22.tsx
  src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/NonMember/Meeting/Meeting.tsx
  src/pages/TeamIntro/TeamIntro.tsx
  src/pages/TeamMaking/TeamMaking.tsx
Labels: ✨Feat, 📊 Analytics
