Repository GDG-ZIMEET/ZIMEET-FrontEnd, pull requests merged in 2025-05, with the labels that each got.

#269 [#268] feat, refactor : 3대3 -> 2대2로 변경 , 소켓 연결 실패나 매칭 실패 시 UI 복구 및 사용자 알림
  src/api/Meeting/WebRandom.ts
  src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
  src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/components/MeetingRandom/MeetingRandomMain.tsx
  src/components/MeetingRandom/Modal/Modal.tsx
  src/components/Non-member/Meeting/MakeTeamBox/MakeTeamBox.tsx
Labels: ✨Feat, 🛠️ Refactor

#272 [#270] feat : 학관/ k관 부스 수정
  .firebase/hosting.ZGlzdA.cache
  dist/index.html
  dist/sw.js
  dist/workbox-3e8df8c8.js
  dist/workbox-5ffe50d4.js
  src/components/Booth/Booths/Booths.tsx
  src/components/Booth/Booths/Styles.ts
  src/components/Booth/Booths/boothsData.ts
  src/components/Booth/TypeButton/TypeButton.tsx
  src/pages/SetList/Styles.ts
  src/utils/SetListUtils.ts
  vite.config.ts
Labels: 🛠️ Refactor

#273 [#264] FCM 알림 세팅 및 구현
  dist/index.html
  public/firebase-messaging-sw.js
  src/components/Chatting/ChattingInventory/Teams/Teams.tsx
  src/components/MyPage/Event/Styles.ts
  src/firebase/firebaseConfig.ts
  src/firebase/useFCM.ts
  src/pages/FCMTest.tsx
  vite.config.ts
Labels: ✨Feat, 📬 API, ⚙️ Chore

#277 [#274] 알림설정 UI 구현
  src/assets/icon/notification.svg
  src/components/MyPage/QnA/QnA.jsx
  src/components/MyPage/QnA/Styles.js
  src/components/OurTeamIntro/Modal/NotificationButton/NotificationButton.tsx
  src/components/OurTeamIntro/Modal/NotificationButton/Styles.ts
  src/pages/OurTeamIntro/OurTeamIntro.tsx
  src/pages/OurTeamIntro/Styles.ts
Labels: ✨Feat, 🎨 Design

#278 [#276] 카카오톡 채널, 이체 확인 링크 수정
  src/components/MyPage/QnA/QnA.jsx
  src/components/MyPage/StoreInfoButton/StoreInfoButton.tsx
  src/components/MyPage/StoreInfoButton/Styles.ts
  src/pages/MyPage/MyPage/MyPage.tsx
Labels: 🚨 BugFix

#284 [#279] 알림설정 UI 구현 및 로직 BUGFIX
  src/components/MyPage/QnA/QnA.jsx
  src/components/OurTeamIntro/Modal/NotificationButton/NotificationButton.tsx
  src/firebase/useFCM.ts
  src/pages/Meeting22/Profile1to1/Profile1to1.tsx
  src/pages/Meeting22/Profile1to1/Styles.ts
Labels: ✨Feat, 🚨 BugFix, 🎨 Design
