Repository GDG-ZIMEET/ZIMEET-FrontEnd, pull requests merged in 2025-01, with the labels that each got.

#5 feat: PR Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝Docs

#8 [#1] chore: 라우팅 정리 및 배경 색 변경
  src/App.tsx
  src/components/MainScreen.tsx
  src/pages/Routers.tsx
Labels: ⚙️ Chore

#10 [#9] feat: 랜덤매칭 퍼블리싱
  src/components/MainScreen.tsx
  src/components/MeetingRandom/Help/Help.tsx
  src/components/MeetingRandom/Help/Styles.ts
  src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
  src/components/MeetingRandom/JoinButton/Styles.ts
  src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/components/MeetingRandom/TypeButton/Styles.ts
  src/components/MeetingRandom/TypeButton/TypeButton.tsx
  src/pages/MeetingRandom/MeetingRandom.tsx
  src/pages/MeetingRandom/Styles.ts
Labels: ✨Feat

#12 [#1] design: 색변경(F2F2F2)
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/components/MeetingRandom/TypeButton/Styles.ts
Labels: 🎨 Design

#15 Feat/#13 Amplitude 데이터 분석 툴 연결 및 세팅
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
Labels: ✨Feat, ⚙️ Chore

#17 [#16] feat: 미팅 로딩 퍼블리싱
  package-lock.json
  src/components/MeetingRandom/Help/Help.tsx
  src/components/MeetingRandom/Help/Styles.ts
  src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
  src/components/MeetingRandom/JoinButton/Styles.ts
  src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/pages/MeetingRandom/MeetingRandom.tsx
  src/pages/MeetingRandom/MeetingRoading/MeetingRoading.tsx
  src/pages/MeetingRandom/MeetingRoading/Styles.ts
  src/pages/Routers.tsx
Labels: ✨Feat

#20 [#19] feat: 부스 배치도 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/fonts/futura extra black font.ttf
  src/assets/icon.ts
  src/assets/icon/booth/D grey.svg
  src/assets/icon/booth/D.svg
  src/assets/icon/booth/DGoC CUK.svg
  src/assets/icon/booth/G grey.svg
  src/assets/icon/booth/G.svg
  src/assets/icon/booth/ateway.svg
  src/assets/icon/booth/ating.svg
  src/assets/icon/booth/check.svg
  src/assets/icon/booth/hand.svg
  src/assets/icon/booth/pupplegirl.svg
  src/components/Booth/Booths/Booths.tsx
  src/components/Booth/Booths/Styles.ts
  src/components/Booth/Booths/boothsData.ts
  src/components/Booth/Header/Header.tsx
  src/components/Booth/Header/Styles.ts
  src/components/Booth/TypeButton/Styles.ts
  src/components/Booth/TypeButton/TypeButton.tsx
  src/pages/Booth/Booth.tsx
  src/pages/Booth/Styles.ts
  src/pages/MeetingRandom/MeetingRoading/Styles.ts
  src/pages/MeetingRandom/Styles.ts
  src/styles/GlobalStyles.ts
  src/styles/font.css
Labels: ✨Feat

#21 [#19] fix: 버그수정
  .firebase/hosting.YnVpbGQ.cache
  src/components/Booth/Booths/Styles.ts
  src/pages/MeetingRandom/Styles.ts
Labels: 🚨 BugFix

#24 [#23] refator : 이미지 수정 및 import 부스 수정
  src/assets/emoticon/baseball.svg
  src/assets/emoticon/candy.svg
  src/assets/emoticon/cat.svg
  src/assets/emoticon/cherry blossom.svg
  src/assets/emoticon/chocolate.svg
  src/assets/emoticon/dog.svg
  src/assets/emoticon/drum.svg
  src/assets/emoticon/fire.svg
  src/assets/emoticon/ghost.svg
  src/assets/emoticon/greenapple.svg
  src/assets/emoticon/heart.svg
  src/assets/emoticon/horse.svg
  src/assets/emoticon/medal.svg
  src/assets/emoticon/mike.svg
  src/assets/emoticon/planet.svg
  src/assets/emoticon/redapple.svg
  src/assets/emoticon/rocket.svg
  src/assets/emoticon/rose.svg
  src/assets/emoticon/tulip.svg
  src/assets/icon.ts
  src/assets/icon/MeetingRandom/bird.svg
  src/assets/icon/Vector.svg
  src/assets/icon/booth/DGoCCUK.svg
  src/components/Booth/Header/Header.tsx
  src/components/Booth/Header/Styles.ts
Labels: 🛠️ Refactor

#26 [#23] feat : 모달 및 도움말 페이지 퍼블리싱
  .firebase/hosting.YnVpbGQ.cache
  src/assets/Icons.ts
  src/components/MeetingRandom/Help/Help.tsx
  src/components/MeetingRandom/Help/Styles.ts
  src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
  src/components/MeetingRandom/JoinButton/Styles.ts
  src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/components/MeetingRandom/Modal/Modal.tsx
  src/components/MeetingRandom/Modal/Styles.ts
  src/components/MeetingRandom/TypeButton/Styles.ts
  src/pages/MeetingRandom/Help/Help.tsx
  src/pages/MeetingRandom/Help/Styles.ts
  src/pages/MeetingRandom/MeetingRandom.tsx
  src/pages/MeetingRandom/MeetingRoading/MeetingRoading.tsx
  src/pages/MeetingRandom/Styles.ts
  src/pages/Routers.tsx
Labels: ✨Feat

#32 [#22] feat: 네비게이션바 제작
  package-lock.json
  package.json
  src/components/MainScreen.tsx
  src/components/NavigationBar/NavigationBar.jsx
  src/components/NavigationBar/Styles.js
Labels: ✨Feat

#39 [#38] feat: 로그인 페이지 틀 제작
  src/assets/icon/login/gdgbottomLogo.svg
  src/components/MainScreen.tsx
  src/pages/Authentication/Login/Login.jsx
  src/pages/Authentication/Login/Styles.js
  src/styles/font.css
Labels: ✨Feat

#42 [#34] feat : 부스페이지에서 미팅 탭으로 라우팅버튼 제작
  src/components/GotoMeeting/GotoMeeting.tsx
  src/components/GotoMeeting/Styles.ts
  src/pages/Booth/Booth.tsx
  src/pages/Booth/BoothDetail/BoothDetail.tsx
Labels: ✨Feat

#44 [#43] refactor: 부스 네비게이션 바
  src/components/MeetingRandom/JoinButton/Styles.ts
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/components/MeetingRandom/TypeButton/Styles.ts
  src/pages/MeetingRandom/MeetingRoading/Styles.ts
  src/pages/MeetingRandom/Styles.ts
Labels: 🛠️ Refactor

#45 [#43] refactor: 네비게이션 바 모바일 화면 적용
  src/components/MainScreen.tsx
  src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
  src/components/MeetingRandom/MakeTeamBox/Styles.ts
  src/pages/MeetingRandom/Styles.ts
Labels: 🛠️ Refactor

#47 [#46] refactor : 좌우 여백 및 pc환경에서 네비게이션 수정
  .firebase/hosting.YnVpbGQ.cache
  src/components/Booth/Booths/Styles.ts
  src/components/Booth/Header/Styles.ts
  src/components/Booth/TypeButton/Styles.ts
  src/components/BoothDetail/BackHeader/Styles.ts
  src/components/BoothDetail/Explanation/Styles.ts
  src/components/MainScreen.tsx
  src/components/MeetingRandom/TypeButton/Styles.ts
  src/components/NavigationBar/Styles.js
  src/pages/Booth/Styles.ts
Labels: 🛠️ Refactor

#49 [#48] feat : 네비게이션 바 라우팅 수정
  src/components/MainScreen.tsx
  src/components/NavigationBar/NavigationBar.jsx
Labels: ✨Feat

#55 [#38] feat: 로그인페이지 반응형 수정
  src/pages/Authentication/Login/Login.jsx
  src/pages/Authentication/Login/Styles.js
Labels: 🛠️ Refactor

#56 [#51] feat: 회원가입 나이 범위 수정
  src/pages/Authentication/Join/Join.jsx
Labels: 🛠️ Refactor

#57 [#53] feat: 채팅 목록 퍼블리싱
  src/assets/Icons.ts
  src/assets/icon/PinkCircle.svg
  src/components/Chatting/ChattingInventory/ChattingInventoryTypeButton/ChattingInventoryTypeButton.tsx
  src/components/Chatting/ChattingInventory/ChattingInventoryTypeButton/Styles.ts
  src/components/Chatting/ChattingInventory/Teams/Styles.ts
  src/components/Chatting/ChattingInventory/Teams/Teams.tsx
  src/components/GotoMeeting/Styles.ts
  src/components/NavigationBar/NavigationBar.jsx
  src/pages/Chatting/Chatting/Chatting.tsx
  src/pages/Chatting/Chatting/Styles.ts
  src/pages/Chatting/ChattingInventory/ChattingInventory.tsx
  src/pages/Chatting/ChattingInventory/Styles.ts
  src/pages/Routers.tsx
Labels: ✨Feat

#61 [#54] feat: 채팅 기능 구현
  src/api/Chatting/chatingRoom/chatingRoom.ts
  src/components/MainScreen.tsx
  src/pages/Chatting/Chatting/Chatting.tsx
  src/pages/Chatting/Chatting/Styles.ts
Labels: ✨Feat

#62 [#54] refactor: 채팅 수정
  .firebase/hosting.YnVpbGQ.cache
  src/components/Chatting/ChattingInventory/Teams/Teams.tsx
  src/components/MainScreen.tsx
  src/pages/Chatting/Chatting/Chatting.tsx
  src/pages/Chatting/Chatting/Styles.ts
Labels: 🛠️ Refactor

#63 [#29] feat: zimeet 소개페이지
  src/assets/Icons.ts
  src/assets/icon/ZIMEET.svg
  src/components/Booth/Header/Header.tsx
  src/components/MainScreen.tsx
  src/pages/Introduct/ZimeetIntroduct/Styles.ts
  src/pages/Introduct/ZimeetIntroduct/ZimeetIntroduct.tsx
  src/pages/Routers.tsx
Labels: ✨Feat

#65 [#51] feat: 회원가입 페이지1 반응형 수정
  src/pages/Authentication/Join/Styles.js
Labels: 🛠️ Refactor

#66 [#51] feat: 회원가입 페이지3 틀 제작
  src/pages/Authentication/Join/Join3.jsx
  src/pages/Authentication/Join/Styles3.js
  src/pages/Routers.tsx
Labels: ✨Feat

#70 [#69] refactor: 채팅 , 사이드바 구현
  .firebase/hosting.YnVpbGQ.cache
  src/assets/Icons.ts
  src/assets/icon/ChattingButton.svg
  src/assets/icon/Hamburger.svg
  src/components/Chatting/Chat/ChattingBox/ChattingBox.tsx
  src/components/Chatting/Chat/ChattingBox/Styles.ts
  src/components/Chatting/Chat/Header/ChatHeader.tsx
  src/components/Chatting/Chat/Header/Styles.ts
  src/components/Chatting/Chat/Input/ChatInputBox.tsx
  src/components/Chatting/Chat/Input/Styles.ts
  src/components/Chatting/Chat/Sidebar/ChatSidebar.tsx
  src/components/Chatting/Chat/Sidebar/Styles.ts
  src/components/Chatting/ChattingInventory/Teams/Styles.ts
  src/components/MainScreen.tsx
  src/pages/Chatting/Chatting/Chatting.tsx
  src/pages/Chatting/Chatting/Styles.ts
Labels: ✨Feat, 🛠️ Refactor

#76 [#75] feat : 팀생성 모달, 버튼 라우팅 생성
  src/components/Meeting22/TeamMaking/MakingButton/MakingButton.tsx
  src/components/Meeting22/TeamMaking/MakingButton/SituationText.tsx
  src/components/Meeting22/TeamMaking/MakingButton/Styles.ts
  src/components/Meeting22/TeamMaking/Profile/AgeBox/AgeBox.tsx
  src/components/Meeting22/TeamMaking/Profile/AgeBox/Styles.ts
  src/components/Meeting22/TeamMaking/Profile/MyProfile.tsx
  src/components/Meeting22/TeamMaking/Profile/ProfileData.ts
  src/components/Meeting22/TeamMaking/Profile/ProfileDetail/ProfileDetail.tsx
  src/components/Meeting22/TeamMaking/Profile/ProfileDetail/Styles.ts
  src/components/Meeting22/TeamMaking/Profile/Styles.ts
  src/components/Meeting22/TeamMaking/TeamName/Styles.ts
  src/components/Meeting22/TeamMaking/TeamName/TeamName.tsx
  src/components/Meeting22/TeamMaking/Teams/MyProfile/MyProfile.tsx
  src/components/Meeting22/TeamMaking/Teams/MyProfile/ProfileData.ts
  src/components/Meeting22/TeamMaking/Teams/MyProfile/Styles.ts
  src/components/Meeting22/TeamMaking/Teams/PeoplePlusButton/Modal/Styles.ts
  src/components/Meeting22/TeamMaking/Teams/PeoplePlusButton/Modal/TeamMemberModal.tsx
  src/components/Meeting22/TeamMaking/Teams/PeoplePlusButton/PeoplePlusButton.tsx
  src/components/Meeting22/TeamMaking/Teams/Styles.ts
  src/components/Meeting22/TeamMaking/Teams/Teams.tsx
  src/pages/Meeting22/TeamMaking/TeamMaking.tsx
Labels: ✨Feat

#78 [#77] refactor : 팀 생성 폴더 구조 바꾸기
  src/components/Meeting22/TeamMaking/Buttons/MakingButton/MakingButton.tsx
  src/components/Meeting22/TeamMaking/Buttons/MakingButton/SituationText.tsx
  src/components/Meeting22/TeamMaking/Buttons/MakingButton/Styles.ts
  src/components/Meeting22/TeamMaking/Buttons/PlusButton/PeoplePlusButton.tsx
  src/components/Meeting22/TeamMaking/Buttons/PlusButton/Styles.ts
  src/components/Meeting22/TeamMaking/Modal/Styles.ts
  src/components/Meeting22/TeamMaking/Modal/TeamMemberModal.tsx
  src/components/Meeting22/TeamMaking/Teams/Teams.tsx
  src/pages/Meeting22/TeamMaking/TeamMaking.tsx
Labels: 🛠️ Refactor

#85 [#51] 회원가입 퍼블리싱 완료
  src/components/Join/Modal.jsx
  src/components/Join/StylesModal.js
  src/pages/Authentication/Join/Join.jsx
  src/pages/Authentication/Join/Join2.jsx
  src/pages/Authentication/Join/Join3.jsx
  src/pages/Authentication/Join/SelectEmoji.jsx
  src/pages/Authentication/Join/Styles.js
  src/pages/Authentication/Join/Styles2.js
  src/pages/Authentication/Join/Styles3.js
  src/pages/Authentication/Join/StylesEmoji.js
  src/pages/Routers.tsx
  src/recoil/state/emojiState.js
Labels: 🛠️ Refactor

#87 [#86] 마이페이지 퍼블리싱
  src/assets/Icons.ts
  src/assets/icon/MyPage/EditMyInfo.svg
  src/components/MyPage/Event/Event.jsx
  src/components/MyPage/Event/Styles.js
  src/components/MyPage/ItemShop/Hi22/ItemHi22.jsx
  src/components/MyPage/ItemShop/Hi22/Styles.js
  src/components/MyPage/ItemShop/Hi33/ItemHi33.jsx
  src/components/MyPage/ItemShop/Hi33/Styles.js
  src/components/MyPage/ItemShop/ItemBanner/ItemBanner.jsx
  src/components/MyPage/ItemShop/ItemBanner/Styles.js
  src/components/MyPage/ItemShop/Main/ItemShop.jsx
  src/components/MyPage/ItemShop/Main/Styles.js
  src/components/MyPage/ItemShop/Tickets/Styles.js
  src/components/MyPage/ItemShop/Tickets/Tickets.jsx
  src/components/MyPage/QnA/QnA.jsx
  src/components/MyPage/QnA/Styles.js
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/Styles.js
  src/pages/Routers.tsx
Labels: ✨Feat

#102 [#101] chore: api 두번 호출 방지
  src/api/booth/Getbooths.ts
  src/components/Booth/Booths/Booths.tsx
  src/index.tsx
Labels: ⚙️ Chore
